wandb:
  mode: online
  project_name: zeroptim
  run_name: null

env:
  device: cpu
  dtype: float32
  seed: 42

dataset:
  task: classification
  name: mnist-digits
  params:
    batch_size: 64
    shuffle: true
    split: train

model:
  model_type: mlp
  model_hparams:
    input_dim: 784
    hidden_dims: [1024, 256, 32]
    output_dim: 10
    act_func: relu
    bias: true
    p_dropout: 0.0
    batch_norm: false
    init: xavier_uniform

optim:
  criterion_type: cross_entropy
  optimizer_type: sgd
  opt_params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 1.0e-4
    nesterov: false

optim:
  criterion_type: cross_entropy
  optimizer_type: adam
  opt_params:
    lr: 0.001
    weight_decay: 1.0e-4