wandb:
  project_name: zeroptim
  mode: online
  run_name: null
  timestamp: 20240116-083048
env:
  device: cpu
  dtype: float32
  seed: 42
dataset:
  name: mnist-digits
  params:
    batch_size: 64
    shuffle: true
    split: train
  task: classification
model:
  model_type: mlp
  model_hparams:
    in_features: 784
    hidden_features:
    - 1024
    - 256
    - 32
    out_features: 10
    act_func: relu
    bias: true
    p_dropout: 0.0
    use_batch_norm: false
    init: xavier_uniform
optim:
  criterion_type: cross_entropy
  optimizer_type: sgd
  opt_params:
    lr: 0.01
    weight_decay: 0.0001
  epsilon: null
  sub_optimizer_type: null
exp:
  directed: false
  landscape: batch
  n_batch: 10
  layerwise: false
